In [6]:
pip install numpy


  Using cached numpy-2.3.2-cp313-cp313-win_amd64.whl.metadata (60 kB)
Using cached numpy-2.3.2-cp313-cp313-win_amd64.whl (12.8 MB)
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:

import numpy as np

retail_data = np.array([
    [1, 25000, 300, 1200, 10],
    [2, 32000, 450, 1500, 15],
    [3, 28000, 380, 1100, 8],
    [4, 41000, 500, 1600, 20],
    [5, 35000, 420, 1400, 12],
    [6, 27000, 360, 1300, 9],
    [7, 39000, 480, 1700, 18],
    [8, 30000, 400, 1250, 14],
    [9, 45000, 550, 1800, 25],
    [10, 33000, 410, 1450, 11]
])

print(retail_data)

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [5]:
store_id = retail_data[:,0]
sales = retail_data[:,1]
customers = retail_data[:,2]
inventory = retail_data[:,3]
returns = retail_data[:,4]
     

In [ ]:
## Basic Performance Analysis
#1. What is the **total revenue** generated across all stores?
total_rev = sales.sum()
print("total revenue:",total_rev)

total revenue: 335000


In [ ]:
#2. Which store recorded the **highest sales**?
max_sales=sales.argmax()
print(" store id with max sales:",store_id[max_sales] )


 store id with max sales: 9


In [ ]:
#3. Which store recorded the **lowest sales**?
min_sales = sales.argmin()
print("store id with min sal:", store_id[min_sales])




store id with min sal: 1


In [ ]:
#4. What is the **average daily sales** per store?
avg_sal = sales.mean()
print("average sales:", avg_sal)

average sales: 33500.0


In [ ]:
#5. How many stores achieved sales **above ₹35,000**?
above_sale = np.sum(sales>35000)
print("Number of store with sales above 35000:",above_sale)


Number of store with sales above 35000: 3


In [21]:
## Customer Insights
#36. Which store had the **highest customer footfall?
max_customers_index = np.argmax(retail_data[:, 2])
store_with_max_customers = retail_data[max_customers_index, 0]
print("Store ID with Maximum Customers:", store_with_max_customers)
     

Store ID with Maximum Customers: 9


In [22]:
#7. What is the **average number of customers** per store?
average_customers = np.mean(retail_data[:, 2])
print("Average number of customers per store:", average_customers)

Average number of customers per store: 425.0


In [23]:
#8. How many stores have **more than 450 customers**?
customers = np.sum(retail_data[:,2]>450)
print("No of stores more than 450 customers:",customers)


No of stores more than 450 customers: 3


In [24]:
#9. Which store has the **lowest customer count**?
min_customer_index= np.argmin(retail_data[:,2])
store_with_min_cust = retail_data[min_customer_index,0]
print("store with minimum customers:",store_with_min_cust)

store with minimum customers: 1


In [8]:
#10. Is there any store where **high sales do not correspond to high customers**?
# Rank sales and customers (higher value = higher rank)
sales_rank = np.argsort(np.argsort(-sales))
cust_rank = np.argsort(np.argsort(-customers))

# Find mismatches where sales rank is high but customer rank is not
mismatch = store_id[sales_rank < cust_rank]

print("Stores where high sales do not correspond to high customers:", mismatch)


Stores where high sales do not correspond to high customers: [ 5 10]


In [25]:
## Inventory & Returns Analysis
#11. What is the **total inventory** across all stores?
total_inventory = np.sum(retail_data[:, 3])
print("Total Inventory:", total_inventory)


Total Inventory: 14300


In [26]:
#12. Which store has the **highest inventory stock**?
max_inventory = np.argmax(retail_data[:, 3])
store_with_max_inventory = retail_data[max_inventory, 0]
print("Store ID with Maximum Inventory:", store_with_max_inventory)


Store ID with Maximum Inventory: 9


In [27]:
#13. How many stores have **inventory less than 1300 units**?
stores_less_than_1300_inventory = np.sum(retail_data[:, 3] < 1300)
print("Number of stores with inventory less than 1300 units:", stores_less_than_1300_inventory)


Number of stores with inventory less than 1300 units: 3


In [28]:
#14. Which store has the **highest return rate** (returns ÷ inventory)?
return_rates = retail_data[:, 4] / retail_data[:, 3]
max_return_rate_index = np.argmax(return_rates)
store_with_max_return_rate = retail_data[max_return_rate_index, 0]
print("Store ID with the highest return rate:", store_with_max_return_rate)


Store ID with the highest return rate: 9


In [ ]:
#15. Which stores have **returns greater than 15 units**?
stores= np.sum(retail_data[:,4]>15)
print(" stores with returns greater than 15 units:",stores)



 stores with returns greater than 15 units: 3


In [39]:
## Sales & Customer Correlation
#16. Is there a **positive correlation** between sales and customers?
correlation_sales_customers = np.corrcoef(retail_data[:, 1], retail_data[:, 2])[0, 1]
print("Correlation between Sales and Customers:", correlation_sales_customers)

if correlation_sales_customers > 0:
    print("There is a positive correlation between sales and customers.")
else:
    print("There is no linear correlation between sales and customers.")


Correlation between Sales and Customers: 0.9593636912502479
There is a positive correlation between sales and customers.


In [53]:
#17. Which store has **high customer visits but low sales**?
average_customers = np.mean(retail_data[:, 2])
average_sales = np.mean(retail_data[:, 1])

high_customers_low_sales_stores = retail_data[(retail_data[:, 2] > average_customers) & (retail_data[:, 1] < average_sales)]

if high_customers_low_sales_stores.shape[0] > 0:
    print("Stores with high customer visits and low sales:")
    print(high_customers_low_sales_stores)
else:
    print("No stores found with high customer visits and low sales based on average thresholds.")


Stores with high customer visits and low sales:
[[    2 32000   450  1500    15]]


In [54]:
#18. Which store has **low customers but high sales**?
average_customers = np.mean(retail_data[:, 2])
average_sales = np.mean(retail_data[:, 1])

low_customers_high_sales_stores = retail_data[(retail_data[:, 2] < average_customers) & (retail_data[:, 1] > average_sales)]

if low_customers_high_sales_stores.shape[0] > 0:
    print("Stores with low customer visits and high sales:")
    print(low_customers_high_sales_stores)
else:
    print("No stores found with low customer visits and high sales based on average thresholds.")

Stores with low customer visits and high sales:
[[    5 35000   420  1400    12]]


In [55]:
#19. How many stores have **sales per customer above ₹90**?
sales_per_customer_per_store = retail_data[:, 1] / retail_data[:, 2]
stores_above_90_sales_per_customer = np.sum(sales_per_customer_per_store > 90)
print("Number of stores with sales per customer above ₹90:", stores_above_90_sales_per_customer)
     


Number of stores with sales per customer above ₹90: 0


In [56]:
#20. Which stores could **benefit from customer acquisition campaigns** (low customers, high inventory)?
average_customers = np.mean(retail_data[:, 2])
average_inventory = np.mean(retail_data[:, 3])

benefit_Customer_camp = retail_data[(retail_data[:, 2] < average_customers) & (retail_data[:, 3] > average_inventory)]

if benefit_Customer_camp.shape[0] > 0:
    print("Stores that could benefit from customer acquisition campaigns (low customers, high inventory):")
    print(benefit_Customer_camp)
else:
    print("No stores found that meet the criteria for benefiting from customer acquisition campaigns based on average thresholds.")


Stores that could benefit from customer acquisition campaigns (low customers, high inventory):
[[   10 33000   410  1450    11]]


In [49]:
## Profitability & Growth
#21. If profit margin is **20% of sales**, what is the **profit per store**?
profit_per_store = retail_data[:, 1] * 0.20
print("Profit per store:", profit_per_store)


Profit per store: [5000. 6400. 5600. 8200. 7000. 5400. 7800. 6000. 9000. 6600.]


In [50]:
#22. Which store has the **highest profit**?
max_profit_index = np.argmax(profit_per_store)
store_with_max_profit = retail_data[max_profit_index, 0]
print("Store ID with the highest profit:", store_with_max_profit)
print("Details of the store with the highest profit:")
print(retail_data[max_profit_index])


Store ID with the highest profit: 9
Details of the store with the highest profit:
[    9 45000   550  1800    25]


In [51]:
#23. Which store has the **lowest profit**?
min_profit_index = np.argmin(profit_per_store)
store_with_min_profit = retail_data[min_profit_index, 0]
print("Store ID with the highest profit:", store_with_min_profit)
print("Details of the store with the highest profit:")
print(retail_data[min_profit_index])


Store ID with the highest profit: 1
Details of the store with the highest profit:
[    1 25000   300  1200    10]


In [46]:
#24. If sales increase by **10% next month**, what are the **new sales figures**?
new_sales = retail_data[:, 1] * 1.10
print("New sales figures (with 10% increase):", new_sales)


New sales figures (with 10% increase): [27500. 35200. 30800. 45100. 38500. 29700. 42900. 33000. 49500. 36300.]


In [52]:
#25. How will **total profit** change with the 10% sales increase?
current_total_profit = np.sum(profit_per_store)
print("Current Total Profit:", current_total_profit)

new_total_profit = np.sum(new_sales * 0.20) # Assuming profit margin remains 20%
print("New Total Profit (with 10% sales increase):", new_total_profit)

profit_change = new_total_profit - current_total_profit
print("Change in Total Profit:", profit_change)


Current Total Profit: 67000.0
New Total Profit (with 10% sales increase): 73700.0
Change in Total Profit: 6700.0


In [43]:
## Operational Strategy
#26. Which stores need **inventory restocking** based on sales and current stock?
inventory_to_sales_ratio = retail_data[:, 3] / retail_data[:, 1]
threshold = np.mean(inventory_to_sales_ratio) * 0.8 # Using 80% of the average as a threshold

# Identify stores below the threshold
restock_needed_stores_mask = inventory_to_sales_ratio < threshold
restock_needed_stores = retail_data[restock_needed_stores_mask]

if restock_needed_stores.shape[0] > 0:
    print("Stores that might need inventory restocking (low inventory-to-sales ratio):")
    print(restock_needed_stores[:, 0])
else:
    print("No stores found that meet the criteria for potential restocking based on the defined threshold.")


No stores found that meet the criteria for potential restocking based on the defined threshold.


In [42]:
#27. Which stores show **high returns percentage** and might require **quality checks**?
average_return_rate = np.mean(return_rates)
high_return_rate_stores_mask = return_rates > average_return_rate
high_return_rate_stores = retail_data[high_return_rate_stores_mask]

if high_return_rate_stores.shape[0] > 0:
    print("\nStores with a high return rate (above average) that might require quality checks:")
    print(high_return_rate_stores[:, 0])
else:
    print("No stores found with a return rate above the average.")
    



Stores with a high return rate (above average) that might require quality checks:
[2 4 7 8 9]


In [6]:
#28. Which store is the **best performer overall** (sales, customers, inventory turnover)?
import numpy as np
# Handle potential division by zero if any store has zero inventory
inventory_turnover = np.where(retail_data[:, 3] != 0, retail_data[:, 1] / retail_data[:, 3], 0)

# Rank stores based on Sales (higher is better)
sales_rank = np.argsort(np.argsort(retail_data[:, 1])) + 1

# Rank stores based on Customers (higher is better)
customers_rank = np.argsort(np.argsort(retail_data[:, 2])) + 1

# Rank stores based on Inventory Turnover (higher is better)
inventory_turnover_rank = np.argsort(np.argsort(inventory_turnover)) + 1

# Calculate a composite score by summing the ranks
composite_score = sales_rank + customers_rank + inventory_turnover_rank

# Find the index of the store with the highest composite score
best_performer_index = np.argmax(composite_score)

# Get the Store ID of the best performer
best_performer_store_id = retail_data[best_performer_index, 0]

print("Store ID with the highest composite score (Best Performer based on this method):", best_performer_store_id)
print("Composite Scores per store:", composite_score)

Store ID with the highest composite score (Best Performer based on this method): 4
Composite Scores per store: [ 4 15 15 28 21  5 21 14 27 15]


In [7]:
#29. Which store is the **worst performer overall**?
# Handle potential division by zero if any store has zero inventory
inventory_turnover = np.where(retail_data[:, 3] != 0, retail_data[:, 1] / retail_data[:, 3], 0)

# Rank stores based on Sales (lower is better for worst performer)
sales_rank_worst = np.argsort(np.argsort(-retail_data[:, 1])) + 1 # Inverse rank for worst

# Rank stores based on Customers (lower is better for worst performer)
customers_rank_worst = np.argsort(np.argsort(-retail_data[:, 2])) + 1 # Inverse rank for worst

# Rank stores based on Inventory Turnover (lower is better for worst performer)
inventory_turnover_rank_worst = np.argsort(np.argsort(-inventory_turnover)) + 1 # Inverse rank for worst

# Calculate a composite score by summing the inverse ranks
composite_score_worst = sales_rank_worst + customers_rank_worst + inventory_turnover_rank_worst

# Find the index of the store with the lowest composite score (using inverse ranks, lowest score is worst)
worst_performer_index = np.argmin(composite_score_worst)


# Get the Store ID of the worst performer
worst_performer_store_id = retail_data[worst_performer_index, 0]

print("Store ID with the lowest composite score (Worst Performer based on this method):", worst_performer_store_id)
print("Composite Scores per store (based on inverse ranks):", composite_score_worst)


Store ID with the lowest composite score (Worst Performer based on this method): 4
Composite Scores per store (based on inverse ranks): [29 18 18  5 12 28 12 19  6 18]


In [41]:

#30. Which stores can be considered for **expansion** based on strong sales and customer metrics?
average_sales = np.mean(retail_data[:, 1])
average_customers = np.mean(retail_data[:, 2])

expansion_candidates = retail_data[(retail_data[:, 1] > average_sales) & (retail_data[:, 2] > average_customers)]

if expansion_candidates.shape[0] > 0:
    print("Stores that can be considered for expansion (strong sales and customer metrics):")
    print(expansion_candidates[:, 0])
else:
    print("No stores found that meet the criteria for expansion based on average thresholds.")
     


Stores that can be considered for expansion (strong sales and customer metrics):
[4 7 9]
